### ISSUE TITLE
Überarbeitung des Wikis

### ISSUE THREAD

**Issue by OguzMobi** [OguzMobi/Push_Test_3_copy_2#18]
Das [Wiki von Verkehr.NRW](https://github.com/Mobidrom/verkehr.nrw-wiki/wiki) (bitte bereits das verlinkte GitHub-Repository verwenden) soll überarbeitet und unter anderem mit weiteren Inhalten für neue Kolleg:innen gefüllt werden. Dies betrifft (vorläufige Liste):
- [ ] Überarbeitung der vorhandenen Inhalte (#146)
- [ ] Beschreibung der Architektur der GeoServices (GeoServer, GeoCoder, TileService, etc.) (#147)
- [ ] Beschreibung der Datentypen (Datex, GTFS, etc.) (#151)
- [ ] Erstellen eines Templates für den Einsatz von Quarkus (#148)
- [ ] Dokumentation der Skripte für den Start- und Endprozess der AWS-VMs (#142)
- [ ] Überprüfen der codebase-portal-Beschreibung auf Nachvollziehbarkeit (#149)
- [ ] Beschreibung der Typo3-Doku an zentraler Stelle (#150)
